### ISSUE TITLE
The third step seems not performed

### ISSUE THREAD

**Issue by ch8316f5eyu** [michelleapaz/T3E#2]
Hi, thanks the tool!

It seems the third step is not performed.

This is the end of of the log:
`# Counting for TE families/subfamilies...
Alu     1251.0222224411
AluJb   186720.523919374
AluJo   99942.0269172959
Completed in 2 minute(s) and 3 second(s)
Analysis Dox5_Input... 17322803 reads
# Intersecting BED file and REPEATS...
chr1    11505   11675   L1MC5a||
chr1    11678   11780   MER5B|chr1      11685   11824   A00783:990:H5JFMDSX3:2:2169:5321:9455;chr1      11685   11824   A00783:990:H5JFMDSX3:2:2169:5321:9455;chr1      11716   11855   A00783:990:H5JFMDSX3:2:1534:27995:29183;chr1    11739   11878   A00783:990:H5JFMDSX3:2:1534:27995:29183|95;95;64;41
chr1    15265   15355   MIR3|chr1       15260   15399   A00783:990:H5JFMDSX3:2:2342:26205:20729;chr1    15299   15438   A00783:990:H5JFMDSX3:2:2538:14660:25128;chr1    15328   15467   A00783:990:H5JFMDSX3:2:2342:26205:20729|90;56;27
# Counting for TE families/subfamilies...
Alu     1379.42784693047
AluJb   162581.087485273
AluJo   90989.7022871328
Completed in 3 minute(s) and 27 second(s)
`

Nothing else. What's wrong?

Thanks!

**Comment by michelleapaz** [comment]
Hello, Weiyu.

Thanks for your message!

After this reported preprocessing step, another log (specific for the sample you are running) should be created. Now two other python scripts should be running (probabilities.py followed by t3e.py).

Please, check if the actual log file is created and if the python scripts are running. Also, check if you have provided enough memory.

Best,

Michelle

**Comment by ch8316f5eyu** [comment]
Hi, Michelle,

It's very weird, I acknowledged it.

But I encountered it very time, then I have to delete the  code ahead to run it again.

And my memory is 2T, I think it's enough.

Thanks.

**Comment by michelleapaz** [comment]
Hello, 

Definitely, 2TB RAM is enough!

At this stage you should have:
- in the results folder: one folder for each ChIP-seq experiment (samples and input control) containing .bed and _counts.txt files.
- in the references folder: path_dataset.csv file should have been created.

The immediate next step is the calculation of the input-based background probabilities. The "probability" files should be created in the input control subfolder of the results folder.

Let me know if you could find these output files. 

I'd suggest you running the test set provided _or_ only **one** iteration of your own dataset to test it. So I can better help you!

Thank you.

Michelle
