### ISSUE TITLE
Create the "control_sample.txt "

### ISSUE THREAD

**Issue by ngualand** [michelleapaz/T3E#4]
Hi, 

I need to compare the binding sites of 2 ChIP seq experiments and I have 2 samples (control and treated) and their corresponding input files. How can I prepare my "control_sample.txt " file. Should I put in the first line the input files and in the second one the ChIPeed samples? Supose the control file is called A and the treated samples is called B with their respective inputs A_I and B_I, is the following file correct?

A_I    B_I
A     B

Thank you very much for the help

**Comment by michelleapaz** [comment]
Hello,

Thanks for your message.

As I understand your message, the "control_sample.txt" file should be:

A_I	A
B_I	B

Kind regards,

Michelle

**Comment by ngualand** [comment]
Hi Michelle,

Thank you very much for the reply. Now I understand. 

I have ti additional questions. 

- Can I compare the enrichment between 2 samples? For example KO vs WT samples? 

- I m now running the software on about 70 GB bam files (that also contain multimapping reads) do you expect the software working on that files dimension?

Many Thanks.

**Comment by michelleapaz** [comment]
Hi, 

- Using T3E you will obtain as output the enrichment (log2FC) and an associated p-value for each TE family/subfamily ("group") for the KO (A) and WT (B) samples. The comparison between A and B can be seen as how much enrichment of a specific TE group in B is greater compared to A. You can, of course, design your experiment to include replicates as well.

- T3E is able to run files of such sizes, however it depends on the available RAM. It is possible (and suggested in such cases) to down-sample (default is 20 million reads), but you can also use a different number of iterations (default is 100).

What I would suggest you is to run only one iteration and adjust those parameters according to your need.

Best!

Michelle

**Comment by ngualand** [comment]
Many Thanks, 

Nicolò

**Comment by ngualand** [comment]
Thank you very much for the help, 

I have run he software as suggested and everything works smoothly. For some TEs families I have obtained a p.value = 0 (iterations = 100). Should I consider this as highly significant (i.e The p.value is too low to be computable) or Should I consider this an error/warning ?

Thanks, 

Nicol0'

**Comment by michelleapaz** [comment]
Hi Nicolo,

I am glad T3E worked smoothly.

You should consider these cases statistically significant (p-value < 0.01), when using 100 iterations. 

Regards,

Michelle
